### ISSUE TITLE
Write up and publish documentation on how tol-lab-share supports volume tracking

### ISSUE THREAD

**Issue by dasunpubudumal** [sanger/tol-lab-share#143]
**User story**
As developers we need to write and publish proper documentation for `tol-lab-share`. The documentation can include the following:

- An architectural overview on `tol-lab-share`.
- A setting up guide along with instructions on how to set up the underlying infrastructure for `tol-lab-share` to act as a queue consumer.
- About how `tol-lab-share` supports the volume tracking process.

To refer the documentation process already set-up for `traction-service`, please use this story: https://github.com/sanger/traction-service/issues/1394

The documentation should be published in GitHub Pages (e.g. Volume Tracking documentation for [`traction-service`](https://sanger.github.io/traction-service/volume-tracking/))

**Who are the primary contacts for this story**
Dasun, Steve, Stuart

**Who is the nominated tester for UAT**

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Documentation should be published in https://sanger.github.io/tol-lab-share
- [ ] A section should exist in the documentation detailing how `tol-lab-share` supports Volume Tracking.
- [ ] A section should exist on the overall architecture on how `tol-lab-share` consumes messages from RabbitMQ broker(s).

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- https://github.com/sanger/traction-service/issues/1394

**Additional context**
