### ISSUE TITLE
Y24-094: Setup a connection between ToL Lab Share and MultiLIMS Warehouse RMQ

### ISSUE THREAD

**Issue by dasunpubudumal** [sanger/tol-lab-share#95]
**User story**
As a developer, I need to establish the initial structure to create a connection between ToL Lab Share and MultiLIMS Warehouse' RabbitMQ. This is to facilitate asynchronous message passing for Volume Tracking. Please refer to https://github.com/sanger/tol-lab-share/issues/57 for more information about this use case.

Please setup a separate user account for ToL Lab Share to connect with MultiLIMS Warehouse RMQ.

- [x] Create a user account for tol-lab-share to connect with the warehouse RabbitMQ (uat and production)
- [ ] Create a stub processor class similar to [`tol_lab_share/processors/create_labware_processor.py`](https://github.com/sanger/tol-lab-share/blob/022525124ce256a608647399db10e6964252835f/tol_lab_share/processors/create_labware_processor.py) that uses `BasicPublisher` class from `lab-share-lib`.
- [ ] Use `BasicPublisher` class' `publish` method in the stub processor class to set up publishing a message to the warehouse RMQ from tol-lab-share. Message publication to a locally set-up RMQ (that simulates warehouse RMQ) could be tested by writing a small script (e.g. [`tools/demo/publisher.py`](https://github.com/sanger/tol-lab-share/blob/42ae6f78f2b671b56a729820fce84d1509a04846/tools/demo/publisher.py)) by instantiating the skeleton processor. In a [later story](https://github.com/sanger/tol-lab-share/issues/96) we'll extend this stub processor to push aliquots to the warehouse.

The idea behind this story is to create a user account in MLWH RabbitMQ, and set the structure in ToL Lab Share to push some message to the MLWH RabbitMQ instance. In a later story we'll use this connection to push aliquots to MLWH extending the stub processor we've created.

**Who are the primary contacts for this story**
Dasun, Stuart, Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] To successfully pass messages between MultiLIMS Warehouse RMQ and ToL Lab Share.

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/General-Backlog-Items/issues/397

References
This story has a non-blocking relationship with:
- https://github.com/sanger/tol-lab-share/issues/57

**Additional context**

Diagram: [Messaging for Volume Tracking](https://lucid.app/lucidchart/6c8d5b09-4e57-4aba-a7ff-8d2cad161b3d/edit?viewport_loc=1140%2C-72%2C2053%2C977%2CUIRBfRVooFlW&invitationId=inv_9886517c-b0aa-4670-9e87-d820b8ddbba7)
