### ISSUE TITLE
Y24-095: Define a new message processor in ToL Lab Share to consume volume tracking messages

### ISSUE THREAD

**Issue by dasunpubudumal** [sanger/tol-lab-share#96]
**User story**
As a developer, I need to create a new message processor in ToL Lab Share to support volume tracking. For this story, I need to focus on passing an aliquot as the message to reach MLWH Warehouse' RabbitMQ that eventually [shovels](https://www.rabbitmq.com/docs/shovel) it to `aliquot` table in MLWH Warehouse. This message is produced by Traction (https://github.com/sanger/traction-service/issues/1202 and https://github.com/sanger/traction-service/issues/1206) and needs to be consumed by ToL Lab Share.

Please use the AMQP connection and the processor established in https://github.com/sanger/tol-lab-share/issues/95 to send the aliquot message to MultiLIMS Warehouse RMQ. The exchange and the queue of the enterprise RMQ are defined in https://github.com/sanger/General-Backlog-Items/issues/397. Note that at this moment, we do not use schema validations at MultiLIMS Warehouse RMQ.

Please note that delivery failures and schema validation failures for volume tracking messages need to be logged properly.

**Who are the primary contacts for this story**
Dasun, Stuart, Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] To successfully consume messages coming from the exchange for aliquot messages.
- [x] To successfully send the aliquot message to MultiLIMS Warehouse RMQ.
- [x] To handle failures gracefully and log the failures properly. 

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/tol-lab-share/issues/95
- https://github.com/sanger/General-Backlog-Items/issues/397

**References**
This story has a non-blocking relationship with:
- https://github.com/sanger/tol-lab-share/issues/57

**Additional context**

Diagram: [Messaging for Volume Tracking](https://lucid.app/lucidchart/6c8d5b09-4e57-4aba-a7ff-8d2cad161b3d/edit?viewport_loc=1140%2C-72%2C2053%2C977%2CUIRBfRVooFlW&invitationId=inv_9886517c-b0aa-4670-9e87-d820b8ddbba7)

**Comment by dasunpubudumal** [comment]
The task breakdown:

### Housekeeping

- [ ] Investigate [`roles/deploy_tol_stack/templates/tol-lab-share/app_config.py.j2`](https://github.com/sanger/deployment/blob/fe022ed675536ac2f68c86e393de752a62f84db1/roles/deploy_tol_stack/templates/tol-lab-share/app_config.py.j2#L51-L69) to see how and which processor is used to process messages coming from a certain queue.
- [ ] Start the implementation locally by first adding the `RabbitConfig` object into the [`RABBITMQ_SERVERS`](https://github.com/sanger/tol-lab-share/blob/21741f74ab837f3ae7c5496b35241585095460a4/tol_lab_share/config/rabbit.py#L23-L41) list.
- [ ] Set up `tol-lab-share` to connect with `rabbit-dev` in UAT, and try to consume from the queue `tls.volume-tracking`.
- [ ] Investigate how (and where) to push to the warehouse RabbitMQ instance. This will entail figuring out which exchanges and queues that we need to use to push something to the warehouse. Also, this will require to figure out the message enclosing message schema that the warehouse accepts messages with.
- [ ] Replicate the exchanges and queues (vhosts and users aren't probably going to be required to be set up locally) in the local RabbitMQ setup.
- [ ] Push a message to the local RabbitMQ to confirm the workings of the queues and the exchanges.
- [ ] Check if processing the message requires any other validations than the ones done with the schema registry in `lab-share-lib`. If there are, we need to create a `CreateAliquotValidator`.

### Message consumption

- [ ] Use [RedPanda](https://redpanda.uat.psd.sanger.ac.uk/console/) to validate the incoming message **with the correct schema version**. If there is a schema validation failure, **properly log the output**.
- [ ] If required, use the `CreateAliquotValidator` to add custom validations.
- [ ] Prepare the message to be sent to the warehouse RabbitMQ. You can use [`tol_lab_share/messages/rabbit/published/create_labware_feedback_message.py`](https://github.com/sanger/tol-lab-share/blob/5e34c0c4840ff286c08a88740bfcbc264704a965/tol_lab_share/messages/rabbit/published/create_labware_feedback_message.py) as a reference implementation.
- [ ] Invoke `publish` on the message created in step above if validations succeed.

### Testing

- [ ] Use https://rabbit-dev.internal.sanger.ac.uk/ to publish a message to the `tls.volume-tracking` queue.
- [ ] Configure the local `tol-lab-share` instance to consume and publish from UAT instances of respective components. Use the UAT instance of Warehouse RabbitMQ to push the consumed message. You can use http://ware-uat.psd.sanger.ac.uk:15672/#/ to log in to the management console.
- [ ] Finally, head over to the `aliquots` table to check if the record has been persisted correctly.

**Comment by dasunpubudumal** [comment]
## Procedure to test in UAT

1. Testing a local instance of `tol-lab-share` with UAT infrastructure:

![image](https://github.com/user-attachments/assets/73a728a3-c3db-4562-a3c5-6e58dba02d50)

2. Testing a UAT instance of `tol-lab-share` with UAT infrastructure:

![image](https://github.com/user-attachments/assets/c9cba1f3-45f5-40a9-b8a7-ba9dbf2ee058)
